config/routes.rb
PutItInYourFace::Application.routes.draw do

  root :to => "ingredient_lists#new"

  resources :recipes

  resources :ingredient_lists

  resources :ingredients

  resources :apocalypse

  resources :static

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :serving_count, :serving_unit, :calories,
  				  :protein, :calcium

  belongs_to :ingredient_lists
  validates :name, presence: true

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        flash[:notice] = 'Ingredient was successfully created.'
        format.html { redirect_to @ingredient }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        flash[:notice] = 'Ingredient was successfully updated.'
        format.html { redirect_to @ingredient }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    flash[:notice] = 'Ingredient has been deleted.'

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

#	def serving
#		serving_count + " " + serving_unit
#	end
# tried, did not work on first pass, revisit later
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Serving<br />
    <span style="display: none;">
      <%= f.label :serving_count %>
    </span>
    <%= f.text_field :serving_count %>
    <span style="display: none;">
      <%= f.label :serving_unit %>
    </span>
    <%= f.select :serving_unit, options_for_select([["cup", "cup"], ["oz", "oz"], ["tbsp", "tbsp"], ["tsp", "tsp"], ["gram", "gram"], ["whole", "whole"], ["pinch", "pinch"]]) %>
  </div>
  <div class="field">
    <%= f.label :calories %><br />
    <%= f.text_field :calories %>
  </div>
  <div class="field">
    <%= f.label :protein %> in g<br />
    <%= f.text_field :protein %>
  </div>
  <div class="field">
    <%= f.label :calcium %> in mg<br />
    <%= f.text_field :calcium %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Serving</th>
    <th>Calories</th>
    <th>Protein (g)</th>
    <th>Calcium (mg)</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= link_to ingredient.name, ingredient %></td>
    <td><%= ingredient.serving_count %><%= ingredient.serving_unit %></td>
    <td><%= ingredient.calories %></td>
    <td><%= ingredient.protein %></td>
    <td><%= ingredient.calcium %></td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<div class="show_item">
<p>
  <b>Name:</b>
  <%= @ingredient.name %>
</p>
<p>
  <b>Serving:</b>
  <%= @ingredient.serving_count %><%= @ingredient.serving_unit %>
</p>
<p>
  <b>Calories:</b>
  <%= @ingredient.calories %>
</p>
<p>
  <b>Protein (g):</b>
  <%= @ingredient.protein %>
</p>
<p>
  <b>Calcium (mg):</b>
  <%= @ingredient.calcium %>
</p>
</div>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>
<%= link_to "Delete Ingredient",
     		ingredient_path(@ingredient),
     		:method => :delete,
     		:confirm => "Are you sure you want to delete this ingredient?" %>